### ISSUE TITLE
Dados do Empregado

### ISSUE THREAD

**Issue by eduardocalil** [mso13/projeto-tp2#1]
Cada empregado têm:

- [x] nome,
- [x] idade
- [x] data de nascimento
- [x] CPF
- [x] número de identificação da empresa
- [x] salário
- [x] data de entrada a empresa
- [x] setor a que pertence e cargo (auxiliar, técnico,
profissional, diretor de setor tal, diretor de operações ou diretor executivo).

**Comment by mso13** [comment]
Classe "Empregado" criada.
