### ISSUE TITLE
Setar configurações iniciais

### ISSUE THREAD

**Issue by eduardocalil** [mso13/projeto-tp2#3]
Cada setor deve ter no mínimo 15 empregados com todos os dados informados

O salário inicial de cada empregado é:

- Auxiliar: R$ 1500
- Técnico: R$ 3000
- Profissional: R$ 6500
- Diretor de Setor: R$ 9500
- Diretor de Operações: R$ 13000
- Diretor Executivo: R$ 18000

**Obs: técnicos e auxiliares tem vale-transporte de R$350**

**Comment by mso13** [comment]
Método "definirSalario()" criado para a lista de demandas. 
OBS: criado atributo "valeTransporte" e método "definirValeTransporte()".
